/*
 * bt_hid_gamepad.c - Bluetooth LE HID Gamepad for Pico W
 *
 * Implements a BLE HID device using BTstack's GATT HIDS profile.
 * This is the same approach used by Santroller and modern wireless
 * controllers (Switch Pro Controller, DualSense, Xbox Series, etc).
 *
 * Why BLE (not Bluetooth Classic):
 *   The original code used Bluetooth Classic HID (BR/EDR + SDP + L2CAP).
 *   Windows 10/11 handles Classic HID well for standard mice/keyboards,
 *   but guitar/instrument subtypes go through a legacy classification path
 *   that consistently misidentifies the device (shows as mouse, keyboard,
 *   or generic gamepad regardless of SDP subclass settings).
 *
 *   BLE HID (HIDS over GATT) bypasses all of that. Windows reads the
 *   GATT HID Service (UUID 0x1812) and the HID Report Descriptor directly,
 *   then classifies the device purely from the descriptor — no SDP, no
 *   CoD subtype, no legacy driver involvement.
 *
 * How it works:
 *   1. CYW43 is initialized (already done by main.c before bt_hid_init)
 *   2. BTstack GATT server is set up with:
 *        - GAP service (device name)
 *        - HIDS service (HID report descriptor + input report characteristic)
 *   3. BLE advertisements are started — Windows/Android/iOS discover the device
 *   4. On connection: host subscribes to the HIDS Input Report characteristic
 *   5. Reports are sent via hids_device_send_input_report() with the report ID
 *      byte stripped (BLE HIDS manages report ID routing in the GATT layer)
 *
 * Report layout (12 bytes sent over BLE, Report ID 0x01 handled by GATT):
 *   Bytes 0–1:   16 buttons (bit-packed, matches XInput button masks)
 *   Byte  2:     Left trigger  (0–255)
 *   Byte  3:     Right trigger (0–255)
 *   Bytes 4–5:   Left stick X  (−32768 to +32767)
 *   Bytes 6–7:   Left stick Y  (−32768 to +32767)
 *   Bytes 4–5:   Left  stick X (−32768 to +32767) — Whammy
 *   Bytes 8–9:   Right stick X (−32768 to +32767) — unused
 *   Bytes 10–11: Right stick Y (−32768 to +32767) — Tilt
 */

#include "bt_hid_gamepad.h"

#include <string.h>
#include <stdio.h>

#include "pico/stdlib.h"
#include "pico/cyw43_arch.h"
#include "pico/unique_id.h"

#include "btstack.h"
#include "ble/gatt-service/device_information_service_server.h"
#include "ble/gatt-service/hids_device.h"

// ────────────────────────────────────────────────────────────────────────
// GATT Profile Data
//
// IMPORTANT: This is Santroller's exact profile_data[], generated by
// compile_gatt.py from bt.gatt + hids.gatt template. We use it verbatim
// because hids_device.c resolves ATT handles by scanning the database at
// boot, and it expects the FULL hids.gatt structure including:
//   - Input Report  (with READ|WRITE|NOTIFY + ENCRYPTION_KEY_SIZE_16)
//   - Output Report (rumble/LED, we ignore writes but it must exist)
//   - Report Map    (we serve our hid_report_descriptor via att_read callback)
//   - Boot Keyboard Input/Output reports
//   - Boot Mouse Input report
//   - HID Information, HID Control Point
//
// Our hand-written profile_data was missing the Output Report and all Boot
// reports, causing hids_device to write notifications to the wrong ATT
// handle — Windows received garbage or nothing at all.
//
// The device name at handle 0x0003 is served dynamically via att_read_callback.
// All other DYNAMIC characteristics (Report Map, PnP ID, etc.) are handled
// by the hids_device / device_information_service libraries automatically.
// ────────────────────────────────────────────────────────────────────────

static const uint8_t profile_data[] =
{
    // ATT DB Version
    1,

    // 0x0001 PRIMARY_SERVICE-GAP_SERVICE
    0x0a, 0x00, 0x02, 0x00, 0x01, 0x00, 0x00, 0x28, 0x00, 0x18,
    // 0x0002 CHARACTERISTIC-GAP_DEVICE_NAME - READ | DYNAMIC
    0x0d, 0x00, 0x02, 0x00, 0x02, 0x00, 0x03, 0x28, 0x02, 0x03, 0x00, 0x00, 0x2a,
    // 0x0003 VALUE CHARACTERISTIC-GAP_DEVICE_NAME - READ | DYNAMIC
    // Served at runtime via att_read_callback so device name matches g_config.device_name
    0x08, 0x00, 0x03, 0x01, 0x03, 0x00, 0x00, 0x2a,


    // Device Information 180A (full service — all fields DYNAMIC, served by library)
    // 0x0008 PRIMARY_SERVICE-ORG_BLUETOOTH_SERVICE_DEVICE_INFORMATION
    0x0a, 0x00, 0x02, 0x00, 0x08, 0x00, 0x00, 0x28, 0x0a, 0x18,
    // 0x0009 CHARACTERISTIC-MANUFACTURER_NAME_STRING - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x09, 0x00, 0x03, 0x28, 0x02, 0x0a, 0x00, 0x29, 0x2a,
    // 0x000a VALUE
    0x08, 0x00, 0x02, 0x01, 0x0a, 0x00, 0x29, 0x2a,
    // 0x000b CHARACTERISTIC-MODEL_NUMBER_STRING - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x0b, 0x00, 0x03, 0x28, 0x02, 0x0c, 0x00, 0x24, 0x2a,
    // 0x000c VALUE
    0x08, 0x00, 0x02, 0x01, 0x0c, 0x00, 0x24, 0x2a,
    // 0x000d CHARACTERISTIC-SERIAL_NUMBER_STRING - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x0d, 0x00, 0x03, 0x28, 0x02, 0x0e, 0x00, 0x25, 0x2a,
    // 0x000e VALUE
    0x08, 0x00, 0x02, 0x01, 0x0e, 0x00, 0x25, 0x2a,
    // 0x000f CHARACTERISTIC-HARDWARE_REVISION_STRING - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x0f, 0x00, 0x03, 0x28, 0x02, 0x10, 0x00, 0x27, 0x2a,
    // 0x0010 VALUE
    0x08, 0x00, 0x02, 0x01, 0x10, 0x00, 0x27, 0x2a,
    // 0x0011 CHARACTERISTIC-FIRMWARE_REVISION_STRING - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x11, 0x00, 0x03, 0x28, 0x02, 0x12, 0x00, 0x26, 0x2a,
    // 0x0012 VALUE
    0x08, 0x00, 0x02, 0x01, 0x12, 0x00, 0x26, 0x2a,
    // 0x0013 CHARACTERISTIC-SOFTWARE_REVISION_STRING - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x13, 0x00, 0x03, 0x28, 0x02, 0x14, 0x00, 0x28, 0x2a,
    // 0x0014 VALUE
    0x08, 0x00, 0x02, 0x01, 0x14, 0x00, 0x28, 0x2a,
    // 0x0015 CHARACTERISTIC-SYSTEM_ID - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x15, 0x00, 0x03, 0x28, 0x02, 0x16, 0x00, 0x23, 0x2a,
    // 0x0016 VALUE
    0x08, 0x00, 0x02, 0x01, 0x16, 0x00, 0x23, 0x2a,
    // 0x0017 CHARACTERISTIC-IEEE_REGULATORY - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x17, 0x00, 0x03, 0x28, 0x02, 0x18, 0x00, 0x2a, 0x2a,
    // 0x0018 VALUE
    0x08, 0x00, 0x02, 0x01, 0x18, 0x00, 0x2a, 0x2a,
    // 0x0019 CHARACTERISTIC-PNP_ID - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x19, 0x00, 0x03, 0x28, 0x02, 0x1a, 0x00, 0x50, 0x2a,
    // 0x001a VALUE
    0x08, 0x00, 0x02, 0x01, 0x1a, 0x00, 0x50, 0x2a,

    // Human Interface Device 1812 — FULL hids.gatt template (required by hids_device.c)
    // 0x001b PRIMARY_SERVICE-ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE
    0x0a, 0x00, 0x02, 0x00, 0x1b, 0x00, 0x00, 0x28, 0x12, 0x18,
    // 0x001c CHARACTERISTIC-PROTOCOL_MODE - DYNAMIC | READ | WRITE_WITHOUT_RESPONSE
    0x0d, 0x00, 0x02, 0x00, 0x1c, 0x00, 0x03, 0x28, 0x06, 0x1d, 0x00, 0x4e, 0x2a,
    // 0x001d VALUE
    0x08, 0x00, 0x06, 0x01, 0x1d, 0x00, 0x4e, 0x2a,
    // 0x001e CHARACTERISTIC-REPORT (Input) - DYNAMIC | READ | WRITE | NOTIFY | ENCRYPTION_KEY_SIZE_16
    // NOTE: Encryption flags (0x0b,0xf5 / 0x0f,0xf1) are required — Windows BLE HID
    // will not deliver notifications from an unencrypted Input Report characteristic.
    0x0d, 0x00, 0x02, 0x00, 0x1e, 0x00, 0x03, 0x28, 0x1a, 0x1f, 0x00, 0x4d, 0x2a,
    // 0x001f VALUE - READ_ENCRYPTED, WRITE_ENCRYPTED, ENCRYPTION_KEY_SIZE=16
    0x08, 0x00, 0x0b, 0xf5, 0x1f, 0x00, 0x4d, 0x2a,
    // 0x0020 CLIENT_CHARACTERISTIC_CONFIGURATION - READ_ANYBODY, WRITE_ENCRYPTED
    0x0a, 0x00, 0x0f, 0xf1, 0x20, 0x00, 0x02, 0x29, 0x00, 0x00,
    // 0x0021 REPORT_REFERENCE - Report ID=1, Type=Input(1)
    0x0a, 0x00, 0x02, 0x00, 0x21, 0x00, 0x08, 0x29, 0x01, 0x01,
    // 0x0022 CHARACTERISTIC-REPORT (Output) - DYNAMIC | READ | WRITE | WRITE_WITHOUT_RESPONSE | ENCRYPTION_KEY_SIZE_16
    0x0d, 0x00, 0x02, 0x00, 0x22, 0x00, 0x03, 0x28, 0x0e, 0x23, 0x00, 0x4d, 0x2a,
    // 0x0023 VALUE - READ_ENCRYPTED, WRITE_ENCRYPTED, ENCRYPTION_KEY_SIZE=16
    0x08, 0x00, 0x0f, 0xf5, 0x23, 0x00, 0x4d, 0x2a,
    // 0x0024 REPORT_REFERENCE - Report ID=1, Type=Output(2)
    0x0a, 0x00, 0x02, 0x00, 0x24, 0x00, 0x08, 0x29, 0x01, 0x02,
    // 0x0025 CHARACTERISTIC-REPORT_MAP - DYNAMIC | READ
    0x0d, 0x00, 0x02, 0x00, 0x25, 0x00, 0x03, 0x28, 0x02, 0x26, 0x00, 0x4b, 0x2a,
    // 0x0026 VALUE
    0x08, 0x00, 0x02, 0x01, 0x26, 0x00, 0x4b, 0x2a,
    // 0x0027 CHARACTERISTIC-BOOT_KEYBOARD_INPUT_REPORT - DYNAMIC | READ | WRITE | NOTIFY
    0x0d, 0x00, 0x02, 0x00, 0x27, 0x00, 0x03, 0x28, 0x1a, 0x28, 0x00, 0x22, 0x2a,
    // 0x0028 VALUE
    0x08, 0x00, 0x0a, 0x01, 0x28, 0x00, 0x22, 0x2a,
    // 0x0029 CLIENT_CHARACTERISTIC_CONFIGURATION
    0x0a, 0x00, 0x0e, 0x01, 0x29, 0x00, 0x02, 0x29, 0x00, 0x00,
    // 0x002a CHARACTERISTIC-BOOT_KEYBOARD_OUTPUT_REPORT - DYNAMIC | READ | WRITE | WRITE_WITHOUT_RESPONSE
    0x0d, 0x00, 0x02, 0x00, 0x2a, 0x00, 0x03, 0x28, 0x0e, 0x2b, 0x00, 0x32, 0x2a,
    // 0x002b VALUE
    0x08, 0x00, 0x0e, 0x01, 0x2b, 0x00, 0x32, 0x2a,
    // 0x002c CHARACTERISTIC-BOOT_MOUSE_INPUT_REPORT - DYNAMIC | READ | WRITE | NOTIFY
    0x0d, 0x00, 0x02, 0x00, 0x2c, 0x00, 0x03, 0x28, 0x1a, 0x2d, 0x00, 0x33, 0x2a,
    // 0x002d VALUE
    0x08, 0x00, 0x0a, 0x01, 0x2d, 0x00, 0x33, 0x2a,
    // 0x002e CLIENT_CHARACTERISTIC_CONFIGURATION
    0x0a, 0x00, 0x0e, 0x01, 0x2e, 0x00, 0x02, 0x29, 0x00, 0x00,
    // 0x002f CHARACTERISTIC-HID_INFORMATION - READ
    0x0d, 0x00, 0x02, 0x00, 0x2f, 0x00, 0x03, 0x28, 0x02, 0x30, 0x00, 0x4a, 0x2a,
    // 0x0030 VALUE - bcdHID=0x0101, bCountryCode=0, flags=0x02 (normally connectable)
    0x0c, 0x00, 0x02, 0x00, 0x30, 0x00, 0x4a, 0x2a, 0x01, 0x01, 0x00, 0x02,
    // 0x0031 CHARACTERISTIC-HID_CONTROL_POINT - DYNAMIC | WRITE_WITHOUT_RESPONSE
    0x0d, 0x00, 0x02, 0x00, 0x31, 0x00, 0x03, 0x28, 0x04, 0x32, 0x00, 0x4c, 0x2a,
    // 0x0032 VALUE
    0x08, 0x00, 0x04, 0x01, 0x32, 0x00, 0x4c, 0x2a,

    // END
    0x00, 0x00,
};

// ────────────────────────────────────────────────────────────────────────
// HID Report Descriptor
//
// Usage (Game Pad, 0x05) → Windows places this in the game controllers list.
// Report ID 0x01 → required for BLE HIDS multi-report devices.
//
// Report data layout (12 bytes, after stripping the report ID byte):
//   Bytes 0–1:   16 buttons (bit-packed, XInput-compatible masks)
//   Byte  2:     Left trigger  (0–255)
//   Byte  3:     Right trigger (0–255)
//   Bytes 4–5:   Left stick X  (signed 16-bit) — Whammy
//   Bytes 6–7:   Left stick Y  (signed 16-bit)
//   Bytes 8–9:   Right stick X (signed 16-bit) — unused
//   Bytes 10–11: Right stick Y (signed 16-bit) — Tilt
// ────────────────────────────────────────────────────────────────────────

static const uint8_t hid_report_descriptor[] = {
    0x05, 0x01,        // Usage Page (Generic Desktop)
    0x09, 0x05,        // Usage (Game Pad)
    0xA1, 0x01,        // Collection (Application)

    0x85, 0x01,        //   Report ID (1)  ← required for BLE HIDS

    // ── 16 Buttons ──
    0x05, 0x09,        //   Usage Page (Button)
    0x19, 0x01,        //   Usage Minimum (Button 1)
    0x29, 0x10,        //   Usage Maximum (Button 16)
    0x15, 0x00,        //   Logical Minimum (0)
    0x25, 0x01,        //   Logical Maximum (1)
    0x95, 0x10,        //   Report Count (16)
    0x75, 0x01,        //   Report Size (1)
    0x81, 0x02,        //   Input (Data, Variable, Absolute)

    // ── Triggers (2 × 8-bit unsigned) ──
    0x05, 0x02,        //   Usage Page (Simulation Controls)
    0x09, 0xC5,        //   Usage (Brake)       — Left Trigger
    0x09, 0xC4,        //   Usage (Accelerator) — Right Trigger
    0x15, 0x00,        //   Logical Minimum (0)
    0x26, 0xFF, 0x00,  //   Logical Maximum (255)
    0x95, 0x02,        //   Report Count (2)
    0x75, 0x08,        //   Report Size (8)
    0x81, 0x02,        //   Input (Data, Variable, Absolute)

    // ── Analog Sticks (4 × 16-bit signed) ──
    0x05, 0x01,        //   Usage Page (Generic Desktop)
    0x09, 0x30,        //   Usage (X)  — Left Stick X / Whammy
    0x09, 0x31,        //   Usage (Y)  — Left Stick Y
    0x09, 0x33,        //   Usage (Rx) — Right Stick X (unused)
    0x09, 0x34,        //   Usage (Ry) — Right Stick Y / Tilt
    0x16, 0x00, 0x80,  //   Logical Minimum (−32768)
    0x26, 0xFF, 0x7F,  //   Logical Maximum (+32767)
    0x95, 0x04,        //   Report Count (4)
    0x75, 0x10,        //   Report Size (16)
    0x81, 0x02,        //   Input (Data, Variable, Absolute)

    0xC0               // End Collection
};

// ATT read callback — serves the GAP Device Name characteristic dynamically.
// This lets the GATT device name match whatever name was passed to bt_hid_init()
// (e.g. from g_config.device_name) rather than being a static compile-time string.
// _bt struct is declared below; use a forward declaration here.
#define GAP_DEVICE_NAME_HANDLE 0x0003
// (defined after _bt struct — see att_read_callback below)
static uint16_t att_read_callback(hci_con_handle_t connection_handle,
                                   uint16_t att_handle,
                                   uint16_t offset,
                                   uint8_t *buffer,
                                   uint16_t buffer_size);
//
// Tells nearby devices:
//   - General discoverable, BLE only (BR/EDR not supported flag)
//   - Device name
//   - Advertises HID Service UUID (0x1812) — Windows needs this to
//     classify as a HID device during discovery before pairing
//   - Appearance = 0x03C4 (HID Gamepad) — shows gamepad icon in BT settings
// ────────────────────────────────────────────────────────────────────────

// Appearance value: Gamepad = 0x03C4 (Category 15 = HID, Sub-category 4 = Gamepad)
#define BLE_APPEARANCE_GAMEPAD  0x03C4

// Forward declaration — the name bytes are filled in dynamically
// We build the adv packet in bt_hid_init() once we have the device name.
static uint8_t adv_data[31];
static uint8_t adv_data_len = 0;

static void build_adv_data(const char *device_name) {
    uint8_t name_len = (uint8_t)strlen(device_name);
    if (name_len > 20) name_len = 20;  // cap to fit in 31-byte adv payload

    uint8_t *p = adv_data;

    // Flags: General Discoverable | BR/EDR Not Supported
    *p++ = 0x02;
    *p++ = BLUETOOTH_DATA_TYPE_FLAGS;
    *p++ = 0x06;

    // Complete Local Name
    *p++ = 1 + name_len;
    *p++ = BLUETOOTH_DATA_TYPE_COMPLETE_LOCAL_NAME;
    memcpy(p, device_name, name_len);
    p += name_len;

    // 16-bit Service UUID: HID Service (0x1812)
    *p++ = 0x03;
    *p++ = BLUETOOTH_DATA_TYPE_COMPLETE_LIST_OF_16_BIT_SERVICE_CLASS_UUIDS;
    *p++ = ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE & 0xFF;
    *p++ = ORG_BLUETOOTH_SERVICE_HUMAN_INTERFACE_DEVICE >> 8;

    // Appearance: Gamepad (0x03C4)
    *p++ = 0x03;
    *p++ = BLUETOOTH_DATA_TYPE_APPEARANCE;
    *p++ = BLE_APPEARANCE_GAMEPAD & 0xFF;
    *p++ = BLE_APPEARANCE_GAMEPAD >> 8;

    adv_data_len = (uint8_t)(p - adv_data);
}

// ────────────────────────────────────────────────────────────────────────
// State
// ────────────────────────────────────────────────────────────────────────

static struct {
    hci_con_handle_t con_handle;   // BLE connection handle (HCI_CON_HANDLE_INVALID = not connected)
    bool             connected;
    bt_hid_report_t  pending;      // Buffered report
    bool             send_pending;
    bt_hid_report_t  last_sent;    // Last report successfully handed to ATT
    bool             have_last_sent;
    uint32_t         send_fail_count;
    const char      *device_name;
} _bt;

static void print_conn_interval(const char *label, uint16_t conn_interval, uint16_t latency) {
    printf("BT: %s interval %u.%02u ms, latency %u\n",
           label,
           conn_interval * 125 / 100,
           25 * (conn_interval & 3),
           latency);
}

// ATT read callback implementation (forward-declared above, after profile_data).
// Serves the GAP Device Name at handle 0x0003 from _bt.device_name at runtime.
static uint16_t att_read_callback(hci_con_handle_t connection_handle,
                                   uint16_t att_handle,
                                   uint16_t offset,
                                   uint8_t *buffer,
                                   uint16_t buffer_size) {
    (void)connection_handle;
    if (att_handle == GAP_DEVICE_NAME_HANDLE && _bt.device_name) {
        return att_read_callback_handle_blob(
            (const uint8_t *)_bt.device_name,
            (uint16_t)strlen(_bt.device_name),
            offset, buffer, buffer_size);
    }
    return 0;
}

// ────────────────────────────────────────────────────────────────────────
// Packet Handler
// ────────────────────────────────────────────────────────────────────────

static void packet_handler(uint8_t packet_type, uint16_t channel, uint8_t *packet, uint16_t size) {
    (void)channel;
    (void)size;

    if (packet_type != HCI_EVENT_PACKET) return;

    switch (hci_event_packet_get_type(packet)) {

        case HCI_EVENT_DISCONNECTION_COMPLETE:
            _bt.con_handle   = HCI_CON_HANDLE_INVALID;
            _bt.connected    = false;
            _bt.send_pending = false;
            _bt.have_last_sent = false;
            printf("BT: Disconnected — re-enabling advertisements\n");
            // ── BUG FIX 1: re-enable advertisements so Windows can find us again ──
            // Without this, the device vanishes after the first disconnect and
            // Windows can never reconnect because we stop advertising.
            gap_advertisements_enable(1);
            break;

        // SM (Security Manager) — BLE pairing events
        case SM_EVENT_JUST_WORKS_REQUEST:
            sm_just_works_confirm(sm_event_just_works_request_get_handle(packet));
            break;

        case SM_EVENT_NUMERIC_COMPARISON_REQUEST:
            sm_numeric_comparison_confirm(sm_event_passkey_display_number_get_handle(packet));
            break;

        case SM_EVENT_PAIRING_COMPLETE:
            if (sm_event_pairing_complete_get_status(packet) == ERROR_CODE_SUCCESS) {
                printf("BT: Pairing complete\n");
            } else {
                printf("BT: Pairing failed (status=%u)\n",
                       sm_event_pairing_complete_get_status(packet));
            }
            break;

        // BLE connection events
        case HCI_EVENT_LE_META:
            switch (hci_event_le_meta_get_subevent_code(packet)) {
                case HCI_SUBEVENT_LE_CONNECTION_COMPLETE:
                    if (hci_subevent_le_connection_complete_get_status(packet) == ERROR_CODE_SUCCESS) {
                        print_conn_interval(
                            "LE connection complete:",
                            hci_subevent_le_connection_complete_get_conn_interval(packet),
                            hci_subevent_le_connection_complete_get_conn_latency(packet));
                    } else {
                        printf("BT: LE connection failed (status=%u)\n",
                               hci_subevent_le_connection_complete_get_status(packet));
                    }
                    break;

                case HCI_SUBEVENT_LE_CONNECTION_UPDATE_COMPLETE:
                    if (hci_subevent_le_connection_update_complete_get_status(packet) == ERROR_CODE_SUCCESS) {
                        print_conn_interval(
                            "LE connection update:",
                            hci_subevent_le_connection_update_complete_get_conn_interval(packet),
                            hci_subevent_le_connection_update_complete_get_conn_latency(packet));
                    } else {
                        printf("BT: LE connection update failed (status=%u)\n",
                               hci_subevent_le_connection_update_complete_get_status(packet));
                    }
                    break;

                default:
                    break;
            }
            break;

        case L2CAP_EVENT_CONNECTION_PARAMETER_UPDATE_RESPONSE:
            printf("BT: Connection parameter update response: %s (result=0x%02x)\n",
                   l2cap_event_connection_parameter_update_response_get_result(packet) == ERROR_CODE_SUCCESS
                       ? "accepted"
                       : "rejected",
                   l2cap_event_connection_parameter_update_response_get_result(packet));
            break;

        // HIDS (HID Service) events
        case HCI_EVENT_HIDS_META:
            switch (hci_event_hids_meta_get_subevent_code(packet)) {

                case HIDS_SUBEVENT_INPUT_REPORT_ENABLE:
                    _bt.con_handle = hids_subevent_input_report_enable_get_con_handle(packet);
                    _bt.connected  = true;
                    printf("BT: Host subscribed to input reports\n");
                    // ── BUG FIX 3: use a conservative desktop-friendly connection interval ──
                    // min=max=12 (15ms), latency=0, timeout=200 (2000ms)
                    int status = gap_request_connection_parameter_update(_bt.con_handle, 12, 12, 0, 200);
                    if (status != ERROR_CODE_SUCCESS) {
                        printf("BT: Connection parameter update request failed (status=%d)\n", status);
                    }
                    break;

                case HIDS_SUBEVENT_OUTPUT_REPORT_ENABLE:
                    _bt.con_handle = hids_subevent_output_report_enable_get_con_handle(packet);
                    break;

                case HIDS_SUBEVENT_FEATURE_REPORT_ENABLE:
                    _bt.con_handle = hids_subevent_feature_report_enable_get_con_handle(packet);
                    break;

                case HIDS_SUBEVENT_PROTOCOL_MODE:
                    printf("BT: Protocol mode: %s\n",
                           hids_subevent_protocol_mode_get_protocol_mode(packet) ? "Report" : "Boot");
                    break;

                // ── BUG FIX 2: send reports only when BLE stack is ready ──
                // hids_device_send_input_report() calls att_server_notify() internally.
                // If the ATT TX buffer is busy (which happens often at 1kHz vs
                // BLE connection intervals), it silently drops the report and returns
                // an error we weren't checking. The correct pattern is:
                //   1. Call hids_device_request_can_send_now_event() to queue a send
                //   2. Send the actual report only in HIDS_SUBEVENT_CAN_SEND_NOW
                // This guarantees the ATT layer is ready before we write.
                case HIDS_SUBEVENT_CAN_SEND_NOW:
                    if (_bt.send_pending && _bt.con_handle != HCI_CON_HANDLE_INVALID) {
                        bt_hid_report_t report_to_send = _bt.pending;
                        uint8_t  *data     = (uint8_t *)&report_to_send;
                        uint16_t  data_len = sizeof(bt_hid_report_t) - 1; // skip report_id byte
                        uint8_t status = hids_device_send_input_report(_bt.con_handle, data + 1, data_len);
                        if (status == ERROR_CODE_SUCCESS) {
                            _bt.last_sent = report_to_send;
                            _bt.have_last_sent = true;
                            _bt.send_pending = false;
                        } else {
                            _bt.send_fail_count++;
                            printf("BT: Input report send failed (status=%u, failures=%lu)\n",
                                   status, (unsigned long)_bt.send_fail_count);
                            uint8_t retry_status = hids_device_request_can_send_now_event(_bt.con_handle);
                            if (retry_status != ERROR_CODE_SUCCESS) {
                                _bt.send_pending = false;
                                printf("BT: Can-send retry request failed (status=%u)\n",
                                       retry_status);
                            }
                        }
                    }
                    break;

                default:
                    break;
            }
            break;

        default:
            break;
    }
}

// ────────────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────────────

void bt_hid_init(const char *device_name, const uint8_t *static_addr) {
    memset(&_bt, 0, sizeof(_bt));
    _bt.con_handle = HCI_CON_HANDLE_INVALID;
    _bt.device_name = device_name;

    // ── Build advertisement payload ──
    build_adv_data(device_name);

    // ── L2CAP ──
    l2cap_init();

    // ── Security Manager: BLE pairing ──
    sm_init();
    sm_set_io_capabilities(IO_CAPABILITY_NO_INPUT_NO_OUTPUT);
    // Bonding + Secure Connections (matches Santroller)
    sm_set_authentication_requirements(
        SM_AUTHREQ_SECURE_CONNECTION |
        SM_AUTHREQ_MITM_PROTECTION   |
        SM_AUTHREQ_BONDING
    );

    // ── ATT Server (GATT database) ──
    // Pass att_read_callback so the GAP Device Name (handle 0x0003) can be
    // served dynamically from _bt.device_name at runtime.
    att_server_init(profile_data, att_read_callback, NULL);

    // ── Battery Service: fixed at 100% ──

    // ── Device Information Service: PnP ID matching USB VID/PID ──
    device_information_service_server_init();
    // VID source 1 = USB-IF, VID = 0x045E (Microsoft), PID = 0x028E (Xbox 360 controller)
    // Keeps the device recognized as compatible with Xbox controller class
    device_information_service_server_set_pnp_id(1, 0x045E, 0x028E, 0x0114);

    // Set serial number from Pico's unique ID
    char serial[32];
    pico_get_unique_board_id_string(serial, sizeof(serial));
    device_information_service_server_set_serial_number(serial);

    // ── HIDS: HID Device Service ──
    hids_device_init(0, hid_report_descriptor, sizeof(hid_report_descriptor));
    if (static_addr) {
        gap_random_address_set(static_addr);
    }

    // ── GAP: advertisement ──
    // Device name is already embedded in adv_data (Complete Local Name field)
    // and in the GATT GAP service characteristic above.
    // gap_set_local_name() is Classic BT only — it does not exist in BLE.

    uint16_t adv_int_min = 0x0030;  // 30ms
    uint16_t adv_int_max = 0x0030;
    uint8_t  adv_type    = 0;       // ADV_IND — connectable undirected
    bd_addr_t null_addr;
    memset(null_addr, 0, 6);
    gap_advertisements_set_params(adv_int_min, adv_int_max, adv_type, 0, null_addr, 0x07, 0x00);
    gap_advertisements_set_data(adv_data_len, adv_data);
    gap_advertisements_enable(1);

    // ── Register event handlers ──
    static btstack_packet_callback_registration_t hci_cb;
    static btstack_packet_callback_registration_t sm_cb;
    static btstack_packet_callback_registration_t l2cap_cb;
    hci_cb.callback = &packet_handler;
    sm_cb.callback  = &packet_handler;
    l2cap_cb.callback = &packet_handler;
    hci_add_event_handler(&hci_cb);
    sm_add_event_handler(&sm_cb);
    l2cap_add_event_handler(&l2cap_cb);
    hids_device_register_packet_handler(packet_handler);

    // ── Power on ──
    hci_power_control(HCI_POWER_ON);
}

void bt_hid_task(void) {
    // BTstack run loop is driven by cyw43_arch_poll() in main.c — nothing needed here.
}

bool bt_hid_connected(void) {
    return _bt.connected && (_bt.con_handle != HCI_CON_HANDLE_INVALID);
}

bool bt_hid_ready(void) {
    return bt_hid_connected() && !_bt.send_pending;
}

bool bt_hid_send_report(const bt_hid_report_t *report) {
    if (!bt_hid_connected()) return false;

    if (_bt.send_pending &&
        memcmp(report, &_bt.pending, sizeof(bt_hid_report_t)) == 0) {
        return true;
    }

    if (!_bt.send_pending && _bt.have_last_sent &&
        memcmp(report, &_bt.last_sent, sizeof(bt_hid_report_t)) == 0) {
        return true;
    }

    // Buffer the report — the actual send happens in HIDS_SUBEVENT_CAN_SEND_NOW.
    // We must NOT call hids_device_send_input_report() directly here because
    // att_server_notify() (which it calls internally) silently drops the data
    // if the ATT TX buffer is busy. At 1kHz vs BLE connection intervals, the
    // buffer is almost always busy — meaning no reports get through at all.
    //
    // The correct pattern: buffer the latest report, request a send slot,
    // and send in the callback when the BLE stack says it's actually ready.
    // If a new report arrives before the previous one was sent, we overwrite —
    // this is correct for a game controller (latest state always wins).
    memcpy(&_bt.pending, report, sizeof(bt_hid_report_t));

    if (!_bt.send_pending) {
        _bt.send_pending = true;
        uint8_t status = hids_device_request_can_send_now_event(_bt.con_handle);
        if (status != ERROR_CODE_SUCCESS) {
            _bt.send_pending = false;
            _bt.send_fail_count++;
            printf("BT: Can-send request failed (status=%u, failures=%lu)\n",
                   status, (unsigned long)_bt.send_fail_count);
            return false;
        }
    }
    // If send_pending is already true, the latest report is already buffered
    // and the can_send_now callback will pick it up.

    return true;
}
